"""Stage mutation whitelist — Contract Extensibility (TZ §4) + Freeze P0."""

from __future__ import annotations

from typing import FrozenSet

# Fields any stage may read but not write unless listed for that stage.
CORE_IDENTITY_FIELDS: FrozenSet[str] = frozenset({"segment_id", "index"})

# Post-LOCK audio/timing fields (Immutable Segment — Freeze TZ P0).
POST_LOCK_TIMING_AUDIO_FIELDS: FrozenSet[str] = frozenset(
    {
        "start_time",
        "end_time",
        "playback_rate",
        "silence_trim",
        "stretch_factor",
        "start_ms",
        "end_ms",
        "place_start",
        "place_delay_ms",
        "lead_in_ms",
        "playback_duration",
        "tts_ms",
        "actual_duration_ms",
        "file",
        "fitted_file",
        "fitted_ms",
        "tts_file_path",
        "tts_text",
        "tts_status",
        "status",
        "allow_atempo",
        "slot_overflow",
        "overflow_pct",
        "overflow_ms",
        "overflow",
        "container_status",
        "timing_meta",
        "video_stretch_ratio",
        "video_adapt_mode",
        "block_merged_with_next",
        "merge_adjusted_start",
        "merge_adjusted_slot_ms",
        "slot_fit_attempts",
        "conflict_strategy",
        "conflict_status",
        "merged_into",
        "merged_into_id",
        "translation_locked",
        "translation_lock_snapshot",
        "segment_uuid",
        "translation_uuid",
        "tts_uuid",
        "audio_uuid",
        "merge_uuid",
        # RevisionManager / uuid_chain (ensure_project_uuids at audio_timing)
        "adaptation_uuid",
        "source_segment_uuid",
        "owned_text_segment_id",
        "wav_segment_id",
        "identity_binding",
        "tts_lifecycle",
        # P3.1 runtime integrity metadata (not translation text)
        "runtime_history",
        "wav_owner",
        "runtime_registry_path",
        "audio_sha256",
        "audio_bound_uuid",
        "slot_ms",
        # P10/P11 managers + P25 diagnostics (never translation text)
        "overflow_manager",
        "underflow_manager",
        "underflow",
        "underflow_ms",
        "needs_studio",
        "dsal_band",
        "dsal_delta_ms",
        "dsal_applied",
        "duration_match_score",
        "expand_required",
        "compress_required",
        "clause_coverage",
        "adaptation_executed",
        "requires_llm_adaptation",
        "timing_budget",
        "timing_score",
        "text_adaptation_trace",
        # Dub Engine Decision Trace / skip_reason diagnostics (not translation text)
        "adaptation_status",
        "adaptation_skip_reason",
        "adaptation_decision",
        "adaptation_errors",
        "overflow_decision",
        "decision_trace",
        "decision_transitions",
        "decision_trace_report",
        "need_adaptation",
        "need_adaptation_force_reason",
        "original_duration_ms",
        "requires_manual_review",
        "ato_levels",
        "optimizer_levels",
        "closed_loop",
    }
)

STAGE_ALLOWED_MUTATIONS: dict[str, frozenset[str]] = {
    "stt": frozenset({"text", "source_word_map"}),
    "translate": frozenset(
        {
            "text",
            "plain_text",
            "translation_text",
            "translated_text",
            "semantic_text",
            "grammar_text",
            "emotion",
            "tts_emotion",
            "intonation",
            "prosody",
            "timing_meta",
        }
    ),
    "timing_aware_translation": frozenset(
        {
            "text",
            "plain_text",
            "translation_text",
            "timing_meta",
        }
    ),
    "validate": frozenset(
        {
            "text",
            "plain_text",
            "translation_text",
            "translated_text",
            "semantic_text",
            "grammar_text",
            "corrected_text",
            "final_text",
            "text_for_tts",
            "voice_input",
            "timing_text",
            "translation_locked",
            "translation_lock_snapshot",
        }
    ),
    # Post-LOCK stages: timing + audio only (no text).
    "locked": frozenset(POST_LOCK_TIMING_AUDIO_FIELDS),
    "tts": frozenset(
        {
            "tts_text",
            "tts_file_path",
            "playback_duration",
            "status",
            "tts_status",
            "tts_ms",
            "actual_duration_ms",
            "tts_uuid",
            "audio_uuid",
            "tts_lifecycle",
            "runtime_history",
            "wav_owner",
            "runtime_registry_path",
            "audio_sha256",
            "audio_bound_uuid",
            # Duration-delta need_adaptation gate (recognition only; no text rewrite)
            "need_adaptation",
            "need_adaptation_force_reason",
            "adaptation_decision",
            "original_duration_ms",
            # Stage 6 TTS speedup metadata (cache / synth prosody stamps)
            "tts_cache_hit",
            "tts_synth_rate",
            "tts_synth_pitch",
            # Stage 20 / 24 — Ukrainian TTS backend + language identity
            "tts_backend",
            "tts_engine",
            "tts_voice",
            "tts_language",
            "tts_sample_rate",
            "cyrillic_ratio",
            # Absolute path stamps (Stage 24 — audio must not "disappear")
            "file",
            "resolved_path",
            # Stage 22 — Mykyta / tts_uk voice controls
            "tts_rate",
            "tts_pitch",
            "tts_volume",
            "tts_length_scale",
            # Stage 25 §1 — UK hard-lock (`resolve_uk_tts`) may rewrite the
            # per-speaker `voice` from Piper `uk_UA-*-high` / forbidden
            # cross-locale id to the canonical tts_uk short id or the safe
            # Edge uk-UA-* fallback. Recorded via `voice_override_reason`.
            "voice",
            "voice_override_reason",
        }
    ),
    "slot_fit": frozenset(
        {
            "file",
            "fitted_file",
            "fitted_ms",
            "allow_atempo",
            "slot_overflow",
            "overflow_pct",
            "overflow_ms",
            "container_status",
            "timing_meta",
            "place_delay_ms",
            "lead_in_ms",
            "video_stretch_ratio",
            "video_adapt_mode",
            "block_merged_with_next",
            "merge_adjusted_start",
            "merge_adjusted_slot_ms",
            "slot_fit_attempts",
            "playback_rate",
            "silence_trim",
            "stretch_factor",
            "overflow",
            "tts_uuid",
            "audio_uuid",
            "merge_uuid",
            "tts_lifecycle",
            "segment_uuid",
            "translation_uuid",
            "runtime_history",
            "wav_owner",
            "runtime_registry_path",
            "audio_sha256",
            "audio_bound_uuid",
            # Scheduler may stamp timing during the slot_fit stage window
            # (AudioTimingOptimizer / QA / slot_ms derivation). Ownership remains Scheduler.
            "start_ms",
            "end_ms",
            "start_time",
            "end_time",
            "place_start",
            "slot_ms",
            "overflow_manager",
            "underflow_manager",
            "underflow",
            "underflow_ms",
            "needs_studio",
            "timing_budget",
            "timing_score",
            # Decision Trace + overflow strategy stamps (slot_fit / ATO)
            "adaptation_executed",
            "adaptation_status",
            "adaptation_skip_reason",
            "adaptation_decision",
            "adaptation_errors",
            "overflow_decision",
            "decision_trace",
            "decision_transitions",
            "decision_trace_report",
            "need_adaptation",
            "need_adaptation_force_reason",
            "original_duration_ms",
            "requires_manual_review",
            "requires_llm_adaptation",
            "text_adaptation_trace",
            "ato_levels",
            "optimizer_levels",
            "closed_loop",
            "dsal_applied",
            "dsal_band",
            "dsal_delta_ms",
        }
    ),
    # MASTER TZ v3.0 — AudioTimingOptimizer stage (separate from slot_fit snapshot)
    "audio_timing": frozenset(POST_LOCK_TIMING_AUDIO_FIELDS)
    | frozenset(
        {
            "overflow_manager",
            "underflow_manager",
            "underflow",
            "underflow_ms",
            "needs_studio",
            "timing_budget",
            "timing_score",
            "playback_duration",
            "tts_ms",
            "actual_duration_ms",
            "file",
            "fitted_file",
            "fitted_ms",
            "adaptation_executed",
            "adaptation_status",
            "adaptation_skip_reason",
            "adaptation_decision",
            "overflow_decision",
            "decision_trace",
            "decision_transitions",
            "decision_trace_report",
            "need_adaptation",
            "need_adaptation_force_reason",
            "requires_manual_review",
            "ato_levels",
            "optimizer_levels",
            "text_adaptation_trace",
            # uuid_chain.ensure_project_uuids / ensure_tts_uuid (orchestration)
            "adaptation_uuid",
            "source_segment_uuid",
            "owned_text_segment_id",
            "wav_segment_id",
            "identity_binding",
            "segment_uuid",
            "translation_uuid",
            "tts_uuid",
            "audio_uuid",
            "merge_uuid",
            "tts_lifecycle",
            "runtime_history",
            "wav_owner",
            "audio_sha256",
            "audio_bound_uuid",
            # Meaning Fit / PSA diagnostics stamped alongside optimizer
            "meaning_fit_applied",
            "meaning_fit_attempted",
            "meaning_fit_status",
            "meaning_fit_reason",
            "meaning_fit_method",
            "meaning_fit_source",
            "predicted_tts_ms",
            "residual_overflow_ms",
            "text_adaptation_reason",
            "audio_strategy_reason",
            "needs_manual_review",
            "success",
        }
    ),
    "timing": frozenset(
        {
            "place_delay_ms",
            "lead_in_ms",
            "timing_meta",
            "conflict_strategy",
            "conflict_status",
            "playback_rate",
            "silence_trim",
            "stretch_factor",
            # place_start / start_ms / end_ms — Scheduler only (Freeze P1)
            "runtime_history",
            "tts_lifecycle",
            "wav_owner",
        }
    ),
    "scheduler": frozenset(
        {
            "start_time",
            "end_time",
            "start_ms",
            "end_ms",
            "place_start",
            "place_delay_ms",
            "lead_in_ms",
            "playback_rate",
            "silence_trim",
            "stretch_factor",
            "timing_meta",
            "overflow",
            "overflow_ms",
            "overflow_pct",
            "slot_overflow",
            "conflict_strategy",
            "conflict_status",
            "segment_uuid",
            "translation_uuid",
            "tts_uuid",
            "audio_uuid",
            "merge_uuid",
            "tts_lifecycle",
            "runtime_history",
            "wav_owner",
            "runtime_registry_path",
            "audio_sha256",
            "audio_bound_uuid",
            "slot_ms",
            "overflow_manager",
            "underflow_manager",
            "underflow",
            "underflow_ms",
            "needs_studio",
        }
    ),
    "studio_handoff": frozenset(
        {
            "container_status",
            "overflow_pct",
            "timing_meta",
            "tts_lifecycle",
            "runtime_history",
            "wav_owner",
            "runtime_registry_path",
            "audio_sha256",
            "audio_bound_uuid",
            "segment_uuid",
            "translation_uuid",
            "tts_uuid",
            "audio_uuid",
            "merge_uuid",
            "file",
            "tts_file_path",
        }
    ),
}

# Stages that run after TRANSLATION LOCK — text mutations always forbidden.
POST_LOCK_STAGES: frozenset[str] = frozenset(
    {
        "locked",
        "tts",
        "slot_fit",
        "audio_timing",
        "timing",
        "scheduler",
        "studio_handoff",
        "merge",
        "export",
    }
)


def allowed_fields_for_stage(stage: str) -> frozenset[str]:
    base = set(CORE_IDENTITY_FIELDS)
    base.update(STAGE_ALLOWED_MUTATIONS.get(stage, frozenset()))
    # Keep TTS stage in sync with canonical TTS_ALLOWED_MUTATIONS (Stage 24 stamps).
    if str(stage or "").strip().lower() == "tts":
        try:
            from engines.pipeline_integrity.tts_segment_fields import (
                TTS_ALLOWED_MUTATIONS,
            )

            base.update(TTS_ALLOWED_MUTATIONS)
        except Exception:
            pass
    return frozenset(base)
